(function(){var c={id:"1fc983b4c305d209e7e05d96e713939f",dm:["huanqiu.com","cba.sports.tom.com","huanqiu.uhoop.tom.com","nba.tom.com"],etrk:[],js:"tongji.baidu.com/hm-web/js/",icon:'',br:false,ctrk:false,align:-1,nv:0,vdur:1800000,age:31536000000,rec:1,rp:0,rs:0,trust:0,vcard:0,se:[[1,'baidu.com','word|wd|w',1,'news,tieba,zhidao,,image,video,hi,baike,wenku,opendata,jingyan'],[2,'google.com','q',0,'tbm=isch,tbm=vid,tbm=nws|source=newssearch,tbm=blg,tbm=frm'],[4,'sogou.com','query|keyword',1,'news,mp3,pic,v,gouwu,zhishi,blogsearch'],[6,'search.yahoo.com','p',1,'news,images,video'],[7,'yahoo.cn','q',1,'news,image,music'],[8,'soso.com','w|key',1,'image,video,music,sobar,wenwen,news,baike'],[11,'youdao.com','q',1,'image,news,,mp3,video'],[12,'gougou.com','search',1,',movie,,,,,video'],[13,'bing.com','q',2,'images,videos,news'],[14,'so.com','q',1,'video,news'],[15,'jike.com','q',1,'news,image,video'],[16,'qihoo.com','kw',0,''],[17,'etao.com','q',1,'s,8'],[18,'soku.com','keyword',2,'a'],[19,'easou.com','q',0,''],[20,'glb.uc.cn','keyword|word|q',0,'']]};var g=!0,k=null,l=!1,aa={};function q(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return d?d[3]:k}function r(a){return(a=(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):k)?a.replace(/:\d+$/,""):a};function s(a,b){if(window.sessionStorage)try{window.sessionStorage.setItem(a,b)}catch(d){}}function t(a){return window.sessionStorage?window.sessionStorage.getItem(a):k};function ba(a,b,d){var e;d.h&&(e=new Date,e.setTime(e.getTime()+d.h));document.cookie=a+"="+b+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(e?"; expires="+e.toGMTString():"")+(d.s?"; secure":"")};function u(a,b){var d=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=k;d=window[e]=k;b&&b(a)};d.src=a};var z;function C(){if(!z)try{z=document.createElement("input"),z.type="hidden",z.style.display="none",z.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(z)}catch(a){return l}return g}
function ca(a,b,d){var e=new Date;e.setTime(e.getTime()+d||31536E6);try{window.localStorage?(b=e.getTime()+"|"+b,window.localStorage.setItem(a,b)):C()&&(z.expires=e.toUTCString(),z.load(document.location.hostname),z.setAttribute(a,b),z.save(document.location.hostname))}catch(f){}}
function da(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),d=a.substring(0,b)-0;if(d&&d>(new Date).getTime())return a.substring(b+1)}}else if(C())try{return z.load(document.location.hostname),z.getAttribute(a)}catch(e){}return k};function D(a,b,d){a.attachEvent?a.attachEvent("on"+b,function(b){d.call(a,b)}):a.addEventListener&&a.addEventListener(b,d,l)};var ea;
(ea=function(){function a(){if(!a.d){a.d=g;for(var b=0,d=e.length;b<d;b++)e[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(d){setTimeout(b,1);return}a()}var d=l,e=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,l);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!d)if(d=g,"complete"===document.readyState)a.d=g;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,
l),window.addEventListener("load",a,l);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var e=l;try{e=window.frameElement==k}catch(B){}document.documentElement.doScroll&&e&&b()}})();return function(b){a.d?b():e.push(b)}}()).d=l;var fa=/msie (\d+\.\d+)/i.test(navigator.userAgent),ga=navigator.cookieEnabled,ha=navigator.javaEnabled(),na=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"",oa=window.screen.width+"x"+window.screen.height,pa=window.screen.colorDepth;c.se.push([14,"so.360.cn","q",1,",news"]);c.se.push([14,"v.360.cn","q",1,"so"]);var F=0,H=Math.round(+new Date/1E3),J="https:"==document.location.protocol?"https:":"http:",qa="cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd sb se si st su sw sse v cv lv u api tt".split(" ");function P(){if("undefined"==typeof window["_bdhm_loaded_"+c.id]){window["_bdhm_loaded_"+c.id]=g;var a=this;a.a={};a.b=[];a.q={push:function(){a.p.apply(a,arguments)}};a.e=0;a.i=l;ra(a)}}
P.prototype={getData:function(a){try{var b=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie);return(b?b[2]:k)||t(a)||da(a)}catch(d){}},setData:function(a,b,d){try{ba(a,b,{domain:sa(),path:ta(),h:d}),d?ca(a,b,d):s(a,b)}catch(e){}},p:function(a){if("[object Array]"==={}.toString.call(a)){var b=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};switch(a[0]){case "_trackPageview":if(1<a.length&&a[1].charAt&&"/"==a[1].charAt(0)){this.a.api|=4;this.a.et=0;
this.a.ep="";this.i?(this.a.nv=0,this.a.st=4):this.i=g;var b=this.a.u,d=this.a.su;this.a.u=J+"//"+document.location.host+a[1];this.a.su=document.location.href;Q(this);this.a.u=b;this.a.su=d}break;case "_trackEvent":2<a.length&&(this.a.api|=8,this.a.nv=0,this.a.st=4,this.a.et=4,this.a.ep=b(a[1])+"*"+b(a[2])+(a[3]?"*"+b(a[3]):"")+(a[4]?"*"+b(a[4]):""),Q(this));break;case "_setCustomVar":if(4>a.length)break;var d=a[1],e=a[4]||3;if(0<d&&6>d&&0<e&&4>e){this.e++;for(var f=(this.a.cv||"*").split("!"),m=
f.length;m<d-1;m++)f.push("*");f[d-1]=e+"*"+b(a[2])+"*"+b(a[3]);this.a.cv=f.join("!");a=this.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?this.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):ua()}break;case "_trackOrder":1<a.length&&"[object Object]"==={}.toString.call(a[1])&&(this.a.api|=16,this.a.nv=0,this.a.st=4,this.a.et=94,this.a.ep=aa.r.stringify(a[1]),Q(this))}}}};
function va(){var a=t("Hm_unsent_"+c.id);if(a)for(var a=a.split(","),b=0,d=a.length;b<d;b++)u(J+"//"+decodeURIComponent(a[b]).replace(/^https?:\/\//,""),function(a){R(a)})}function R(a){var b=t("Hm_unsent_"+c.id)||"";b&&((b=b.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?s("Hm_unsent_"+c.id,b):window.sessionStorage&&window.sessionStorage.removeItem("Hm_unsent_"+c.id))}
function wa(a,b){var d=t("Hm_unsent_"+c.id)||"",e=a.a.u?"":"&u="+encodeURIComponent(document.location.href),d=encodeURIComponent(b.replace(/^https?:\/\//,"")+e)+(d?","+d:"");s("Hm_unsent_"+c.id,d)}function Q(a){a.a.rnd=Math.round(2147483647*Math.random());a.a.api=a.a.api||a.e?a.a.api+"_"+a.e:"";var b=J+"//hm.baidu.com/hm.gif?"+xa(a);a.a.api=0;a.e=0;wa(a,b);u(b,function(a){R(a)})}
function ya(a){return function(){a.a.nv=0;a.a.st=4;a.a.et=3;a.a.ep=(new Date).getTime()-a.g.o+","+((new Date).getTime()-a.g.f+a.g.j);Q(a)}}
function ra(a){try{var b,d,e,f,m,B,h;F=a.getData("Hm_lpvt_"+c.id)||0;13==F.length&&(F=Math.round(F/1E3));a:if(document.referrer){for(var p=0,Aa=c.se.length;p<Aa;p++)if(RegExp("(^|\\.)"+c.se[p][1].replace(/\./g,"\\.")).test(r(document.referrer))){var A=q(document.referrer,c.se[p][2])||"";if(A||!(2!=c.se[p][0]&&14!=c.se[p][0]&&17!=c.se[p][0])){1==c.se[p][0]&&-1<document.referrer.indexOf("cpro.baidu.com")&&(A="");a.a.se=c.se[p][0];for(var Ba=a.a,n=c.se[p],I=0,Ca=2==n[3]?n[1]+"\\/":"",Da=1==n[3]?"\\."+
n[1]:"",V=n[4].split(","),n=0,Ea=V.length;n<Ea;n++)if(""!==V[n]&&RegExp(Ca+V[n]+Da).test(document.referrer)){I=n+1;break}Ba.sse=I;a.a.sw=A;d=2;break a}}A=l;S(document.referrer)&&S(document.location.href)?A=g:(I=r(document.referrer),A=T(I||"",document.location.hostname));d=A?H-F>c.vdur?1:4:3}else d=H-F>c.vdur?1:4;b=4!=d?1:0;if(B=a.getData("Hm_lvt_"+c.id)){h=B.split(",");for(var G=h.length-1;0<=G;G--)13==h[G].length&&(h[G]=""+Math.round(h[G]/1E3));for(;2592E3<H-h[0];)h.shift();m=4>h.length?2:3;for(1===
b&&h.push(H);4<h.length;)h.shift();B=h.join(",");f=h[h.length-1]}else B=H,f="",m=1;a.setData("Hm_lvt_"+c.id,B,c.age);a.setData("Hm_lpvt_"+c.id,H);e=H==a.getData("Hm_lpvt_"+c.id)?"1":"0";if(0==c.nv&&S(document.location.href)&&(""==document.referrer||S(document.referrer)))b=0,d=4;a.a.nv=b;a.a.st=d;a.a.cc=e;a.a.lt=f;a.a.lv=m;a.a.si=c.id;a.a.su=document.referrer;a.a.ds=oa;a.a.cl=pa+"-bit";a.a.ln=na;a.a.ja=ha?1:0;a.a.ck=ga?1:0;a.a.lo="number"==typeof _bdhm_top?1:0;var K=a.a;b="";if(navigator.plugins&&
navigator.mimeTypes.length){var X=navigator.plugins["Shockwave Flash"];X&&X.description&&(b=X.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{var ia=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");ia&&(b=ia.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(Ma){}K.fl=b;var L=a.a,K="";try{external.twGetVersion(external.twGetSecurityID(window))&&-1<external.twGetRunPath.toLowerCase().indexOf("360se")&&(K=17)}catch(Na){}L.sb=K;a.a.v="1.0.50";
a.a.cv=decodeURIComponent(a.getData("Hm_cv_"+c.id)||"");1==a.a.nv&&(a.a.tt=document.title||"");a.a.api=0;var v=document.location.href;a.a.cm=q(v,"hmmd")||"";a.a.cp=q(v,"hmpl")||"";a.a.cw=q(v,"hmkw")||"";a.a.ci=q(v,"hmci")||"";a.a.cf=q(v,"hmsr")||"";0==a.a.nv?va():R(".*");if(""!=c.icon){var w,x=c.icon.split("|"),Y="http://tongji.baidu.com/hm-web/welcome/ico?s="+c.id,Z=("http:"==J?"http://eiv":"https://bs")+".baidu.com"+x[0]+"."+x[1];switch(x[1]){case "swf":var ja=x[2],ka=x[3],L="s="+Y,v="HolmesIcon"+
H;w='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+v+'" width="'+ja+'" height="'+ka+'"><param name="movie" value="'+Z+'" /><param name="flashvars" value="'+(L||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+v+'" width="'+ja+'" height="'+ka+'" src="'+Z+'" flashvars="'+(L||"")+'" allowscriptaccess="always" /></object>';break;case "gif":w='<a href="'+Y+'" target="_blank"><img border="0" src="'+Z+'" width="'+x[2]+'" height="'+
x[3]+'"></a>';break;default:w='<a href="'+Y+'" target="_blank">'+x[0]+"</a>"}document.write(w)}var M=document.location.hash.substring(1),Fa=RegExp(c.id),Ga=-1<document.referrer.indexOf("baidu.com")?g:l;if(M&&Fa.test(M)&&Ga){var N=document.createElement("script");N.setAttribute("type","text/javascript");N.setAttribute("charset","utf-8");N.setAttribute("src",J+"//"+c.js+q(M,"jn")+"."+q(M,"sx")+"?"+a.a.rnd);var la=document.getElementsByTagName("script")[0];la.parentNode.insertBefore(N,la)}a.l&&a.l();
a.k&&a.k();if(c.rec||c.trust)a.a.nv?(a.c=encodeURIComponent(document.referrer),window.sessionStorage?s("Hm_from_"+c.id,a.c):ca("Hm_from_"+c.id,a.c,864E5)):a.c=(window.sessionStorage?t("Hm_from_"+c.id):da("Hm_from_"+c.id))||"";a.m&&a.m();a.n&&a.n();a.g=new za;D(window,"beforeunload",ya(a));var y=window._hmt;if(y&&y.length)for(w=0;w<y.length;w++){var E=y[w];switch(E[0]){case "_setAccount":1<E.length&&/^[0-9a-z]{32}$/.test(E[1])&&(a.a.api|=1,window._bdhm_account=E[1]);break;case "_setAutoPageview":if(1<
E.length){var $=E[1];if(l===$||g===$)a.a.api|=2,window._bdhm_autoPageview=$}}}if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var O=window._hmt;if(O&&O.length)for(var y=0,Ia=O.length;y<Ia;y++)a.p(O[y]);window._hmt=a.q}if("undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===g)a.i=g,a.a.et=0,a.a.ep="",Q(a)}catch(ma){a=[],a.push("si="+c.id),a.push("n="+encodeURIComponent(ma.name)),a.push("m="+encodeURIComponent(ma.message)),
a.push("r="+encodeURIComponent(document.referrer)),u(J+"//hm.baidu.com/hm.gif?"+a.join("&"))}}function xa(a){for(var b=[],d=0,e=qa.length;d<e;d++){var f=qa[d],m=a.a[f];"undefined"!=typeof m&&""!==m&&b.push(f+"="+encodeURIComponent(m))}return b.join("&")}
function ua(){var a="Hm_cv_"+c.id;try{if(ba(a,"",{domain:sa(),path:ta(),h:-1}),window.sessionStorage&&window.sessionStorage.removeItem(a),window.localStorage)window.localStorage.removeItem(a);else if(C())try{z.load(document.location.hostname),z.removeAttribute(a),z.save(document.location.hostname)}catch(b){}}catch(d){}}function ta(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&Ha(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"}
function sa(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(T(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a}function S(a){for(var b=0;b<c.dm.length;b++)if(-1<c.dm[b].indexOf("/")){if(Ha(a,c.dm[b]))return g}else{var d=r(a);if(d&&T(d,c.dm[b]))return g}return l}function Ha(a,b){a=a.replace(/^https?:\/\//,"");return 0==a.indexOf(b)}function T(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length==a.length}
P.prototype.l=function(){D(document,"click",Ja(this));for(var a=c.etrk.length,b=0;b<a;b++){var d=c.etrk[b],e=document.getElementById(d.id);e&&D(e,d.eventType,Ka(this))}};function Ka(a){return function(b){(b.target||b.srcElement).setAttribute("HM_fix",b.clientX+":"+b.clientY);a.a.et=1;a.a.ep="{id:"+this.id+",eventType:"+b.type+"}";Q(a)}}
function Ja(a){return function(b){var d=b.target||b.srcElement,e=d.getAttribute("HM_fix"),f=b.clientX+":"+b.clientY;if(e&&e==f)d.removeAttribute("HM_fix");else if(e=c.etrk.length,0<e){for(f={};d&&d!=document.body;)d.id&&(f[d.id]=""),d=d.parentNode;for(d=0;d<e;d++){var m=c.etrk[d];f.hasOwnProperty(m.id)&&(a.a.et=1,a.a.ep="{id:"+m.id+",eventType:"+b.type+"}",Q(a))}}}}
P.prototype.k=function(){var a=this;c.ctrk&&(D(document,"mouseup",La(this)),D(window,"beforeunload",function(){U(a)}),setInterval(function(){U(a)},6E5))};
function La(a){return function(b){var d,e;fa?(e=Math.max(document.documentElement.scrollTop,document.body.scrollTop),d=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),d=b.clientX+d,e=b.clientY+e):(d=b.pageX,e=b.pageY);var f=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:d-=f/2;break;case 2:d-=f}d="{x:"+d+",y:"+e+",";b=b.target||b.srcElement;if("a"!=b.tagName.toLowerCase())a:{for(e="A";(b=b.parentNode)&&1==b.nodeType;)if(b.tagName==
e)break a;b=k}b=d=b?d+("t:a,u:"+encodeURIComponent(b.href)+"}"):d+"t:b}";""!=b&&(d=(J+"//hm.baidu.com/hm.gif?"+xa(a).replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+b+"]"))).length,1024<d+10||(1024<d+encodeURIComponent(a.b.join(",")+(a.b.length?",":"")).length+10&&U(a),a.b.push(b),(10<=a.b.length||/t:a/.test(b))&&U(a)))}}function U(a){0!=a.b.length&&(a.a.et=2,a.a.ep="["+a.b.join(",")+"]",Q(a),a.b=[])}
P.prototype.m=function(){var a=this;c.rec&&ea(function(){if(c.rp&&c.rs&&(!(2==c.rs||4==c.rs)||document.getElementById("hm_t_"+c.rp))){var b=document.createElement("script");b.charset="utf-8";b.src="http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+c.rp,"from="+a.c,"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+Math.round(2147483647*Math.random())].join("&");var d=document.getElementsByTagName("script")[0];d.parentNode.appendChild(b,d)}})};
P.prototype.n=function(){if(c.trust&&c.vcard){var a=document.createElement("script");a.charset="utf-8";a.src="http://trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+this.c,"rnd="+Math.round(2147483647*Math.random())].join("&");var b=document.getElementsByTagName("script")[0];b.parentNode.appendChild(a,b)}};
function za(){this.f=this.o=(new Date).getTime();this.j=0;"object"==typeof document.onfocusin?(D(document,"focusin",W(this)),D(document,"focusout",W(this))):(D(window,"focus",W(this)),D(window,"blur",W(this)))}function W(a){return function(b){if(!(b.target&&b.target!=window)){if("blur"==b.type||"focusout"==b.type)a.j+=(new Date).getTime()-a.f;a.f=(new Date).getTime()}}}new P;})();
