<!-- 百度统计代码 begin -->
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
if(document.location.host=="msn.huanqiu.com"){
	document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F39bc489ef8ff23ec5dc12cd120d4f2b8' type='text/javascript'%3E%3C/script%3E"));
}else{
	document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F1fc983b4c305d209e7e05d96e713939f' type='text/javascript'%3E%3C/script%3E"));
}
<!-- 百度统计代码 end -->
